import { px } from "../combat/constants";
import type { CharacterDef, HitLevelValue, MoveDef, TelegraphDef } from "../combat/types";
import { actionBit, HitLevel } from "../combat/types";

export const BellWardenMoveId = {
  ChainSweep: 101,
  BellHammer: 102,
  GravePulse: 103,
  ChainHook: 104,
} as const;

function move(
  id: number,
  key: string,
  animation: string,
  startup: number,
  active: number,
  recovery: number,
  level: HitLevelValue,
  damage: number,
  box: { x: number; y: number; w: number; h: number },
  telegraph: TelegraphDef,
): MoveDef {
  return {
    id,
    key,
    animation,
    tags: ["boss", "bell-warden", key.replaceAll("_", "-")],
    description: `The Bell Warden's ${key.replaceAll("_", " ")}. Read the warning, defend, then punish the recoil.`,
    duration: startup + active + recovery,
    startup,
    active,
    recovery,
    requiresCrouch: false,
    airOk: false,
    staminaCost: 0,
    hitboxes: [{
      id: 1,
      box: { x: px(box.x), y: px(box.y), w: px(box.w), h: px(box.h) },
      startFrame: startup,
      endFrame: startup + active - 1,
      level,
      damage,
      hitstun: 28,
      blockstun: Math.max(17, Math.trunc(damage / 5)),
      hitstopAttacker: 7,
      hitstopDefender: 10,
      pushbackHitAttacker: px(-1.2),
      pushbackHitDefender: px(7),
      pushbackBlockAttacker: px(-2.4),
      pushbackBlockDefender: px(5),
      launchVelocityY: key === "grave_pulse" ? px(7) : 0,
    }],
    hurtboxWindows: [],
    invulWindows: [],
    armorWindows: [],
    movement: [],
    cancelWindows: [],
    telegraph,
  };
}

const moves = [
  move(BellWardenMoveId.ChainSweep, "chain_sweep", "chain_sweep", 42, 5, 68, HitLevel.Low, 92, { x: 18, y: 0, w: 310, h: 34 }, { startFrame: 0, endFrame: 41, shape: "ground-band", pattern: "diagonal", cue: "chain-rattle" }),
  move(BellWardenMoveId.BellHammer, "bell_hammer", "bell_hammer", 38, 5, 72, HitLevel.Overhead, 118, { x: 10, y: 24, w: 126, h: 150 }, { startFrame: 0, endFrame: 37, shape: "vertical-sigil", pattern: "runes", cue: "bell-rise" }),
  move(BellWardenMoveId.GravePulse, "grave_pulse", "grave_pulse", 36, 7, 58, HitLevel.Low, 80, { x: -30, y: 0, w: 370, h: 28 }, { startFrame: 0, endFrame: 35, shape: "floor-pulse", pattern: "rings", cue: "grave-hum" }),
  move(BellWardenMoveId.ChainHook, "chain_hook", "chain_hook", 31, 4, 54, HitLevel.Mid, 74, { x: 26, y: 42, w: 350, h: 32 }, { startFrame: 0, endFrame: 30, shape: "tracking-line", pattern: "chain", cue: "hook-drag" }),
];

export const BELL_WARDEN: CharacterDef = {
  id: "bell_warden",
  name: "The Bell Warden",
  health: 1800,
  stamina: 240,
  armor: 24,
  resistances: { poison: 15, fire: 10, frost: 20, shock: 5 },
  perks: { graveStep: false, venomEdge: false, staticConductor: false, voidChannel: false, burningBrand: false },
  walkForwardSpeed: px(0.8),
  walkBackwardSpeed: px(0.5),
  dashForward: { velocities: [px(3), px(2), px(1)], attackCancelFrame: 2, staminaCost: 0, recognitionWindow: 12 },
  dashBackward: { velocities: [px(2), px(1)], attackCancelFrame: 1, staminaCost: 0, recognitionWindow: 12 },
  jumpVelocityY: px(6),
  jumpVelocityXForward: px(1),
  jumpVelocityXBackward: px(-1),
  jumpSquatFrames: 8,
  landingFrames: 8,
  gravity: px(0.6),
  groundFriction: px(0.25),
  pushboxStand: { x: px(-70), y: 0, w: px(140), h: px(205) },
  pushboxCrouch: { x: px(-76), y: 0, w: px(152), h: px(160) },
  pushboxAir: { x: px(-66), y: 0, w: px(132), h: px(185) },
  hurtboxesStand: [{ x: px(-68), y: 0, w: px(136), h: px(120) }, { x: px(-58), y: px(120), w: px(116), h: px(85) }],
  hurtboxesCrouch: [{ x: px(-74), y: 0, w: px(148), h: px(156) }],
  hurtboxesAir: [{ x: px(-64), y: 0, w: px(128), h: px(185) }],
  moves,
  commands: moves.map((candidate, slot) => ({
    moveId: candidate.id,
    buttons: actionBit(slot),
    motion: [],
    motionWindow: 0,
    requiresCrouch: false,
    requiresAir: false,
    priority: 20 - slot,
  })),
};
